baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yoroi Theme'
summaryLength = 10
paginate = 6

[params]
#LogoFile = "img/logo.png"
dateFormat = "Jan 2, 2006"
description = "Site Description"
yearStart = ""
#author = 'John Doe'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe= true
